<a href="https://colab.research.google.com/github/Ans365332/6may-file-example/blob/main/Numpy_A_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUMPY---->
#-numpy is basically used for numerical operation on the array
#-It work on the homogeneous data

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4])  #It will create an array from numpy package
arr

array([1, 2, 3, 4])

In [ ]:
a=np.arange(1,11)  # it will create an array for particular range
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.ndim     # it will show the dimension

2

In [ ]:
a.shape  # it will  show row and column

(3, 4)

In [ ]:
a.size  # it will show count of element

12

In [ ]:
a.itemsize  #

8

In [ ]:
c=np.array([[1,2],[3,4]],dtype=float)  # by using dtype we can change the data type of array
c

array([[1., 2.],
       [3., 4.]])

In [ ]:
a=np.zeros((3,4))   # it will create the matrix of 0
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a=np.ones((3,4))    #it will create the matrix of 1
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a=np.empty((3,4))    #It will create a matrix with random number in memory
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a=np.linspace(1,10,5)  #it will create an array with particular range with given no. of element
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
a=np.linspace(1,10,5).reshape(5,1,1) #it will create an array with particular range with given no. of element
a

array([[[ 1.  ]],

       [[ 3.25]],

       [[ 5.5 ]],

       [[ 7.75]],

       [[10.  ]]])

In [ ]:
#--Operations between two array-->

In [ ]:
#Q-Generate an array with the range of 1 to 1000,power(2)
#take two array-->addition , multi, substraction

In [ ]:
a=np.arange(1,1000)
ar=a**2
ar

array([     1,      4,      9,     16,     25,     36,     49,     64,
           81,    100,    121,    144,    169,    196,    225,    256,
          289,    324,    361,    400,    441,    484,    529,    576,
          625,    676,    729,    784,    841,    900,    961,   1024,
         1089,   1156,   1225,   1296,   1369,   1444,   1521,   1600,
         1681,   1764,   1849,   1936,   2025,   2116,   2209,   2304,
         2401,   2500,   2601,   2704,   2809,   2916,   3025,   3136,
         3249,   3364,   3481,   3600,   3721,   3844,   3969,   4096,
         4225,   4356,   4489,   4624,   4761,   4900,   5041,   5184,
         5329,   5476,   5625,   5776,   5929,   6084,   6241,   6400,
         6561,   6724,   6889,   7056,   7225,   7396,   7569,   7744,
         7921,   8100,   8281,   8464,   8649,   8836,   9025,   9216,
         9409,   9604,   9801,  10000,  10201,  10404,  10609,  10816,
        11025,  11236,  11449,  11664,  11881,  12100,  12321,  12544,
      

In [ ]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1+a2

array([5, 7, 9])

In [ ]:
a1-a2

array([-3, -3, -3])

In [ ]:
a1*a2

array([ 4, 10, 18])

In [ ]:
ar1=np.array([[1,2],[3,4]])
ar2=np.array([[5,6],[7,8]])    # it will done the matrix multiplication
a=ar1.dot(ar2)
a

array([[19, 22],
       [43, 50]])

In [ ]:
#Random numbers--->

In [ ]:
#random no. generator
a=np.random.default_rng(1)   # it will create the instance for random number
b=a.random((3,4))     #it will generate random number
b

array([[0.51182162, 0.9504637 , 0.14415961, 0.94864945],
       [0.31183145, 0.42332645, 0.82770259, 0.40919914],
       [0.54959369, 0.02755911, 0.75351311, 0.53814331]])

In [ ]:
a=np.array([1,2,3,4])
a.sum()

np.int64(10)

In [ ]:
a.max()

np.int64(4)

In [ ]:
a.min()

np.int64(1)

In [ ]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [ ]:
arr.sum(axis=1)  #sum of row

array([3, 7])

In [ ]:
arr.sum(axis=0)  #sum of column

array([4, 6])

In [ ]:
a=np.array([1,2,3,4])
a.cumsum()  # it is cummulative sum( like fabonacci series)

array([ 1,  3,  6, 10])

In [ ]:
a=np.arange(0,1000).reshape(10,10,10)
a

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [ ]:
arr=np.ones_like(a) # it will create matrix exactly in dimension like first one but with 1 value
arr

array([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [ ]:
arr2=np.zeros_like(arr)   # it will create matrix exactly in dimension like first one but with 0 value
arr2

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr=np.ones_like(a)
print("Array:",arr)
print("size:",arr.size)
print("shape:",arr.shape)
print("dimension:",arr.ndim)

Array: [[1 1 1]
 [1 1 1]
 [1 1 1]]
size: 9
shape: (3, 3)
dimension: 2


In [ ]:
arr2=np.zeros_like(a)
arr2
print("Array:",arr)
print("size:",arr.size)
print("shape:",arr.shape)
print("dimension:",arr.ndim)

9

In [ ]:
a=np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr=np.empty_like(a)
print("Array:",arr)
print("size:",arr.size)
print("shape:",arr.shape)
print("dimension:",arr.ndim)

Array: [[370917920         0  11672240  11667168  11671848]
 [ 11666144  11669184  11668864  11666632  11669664]
 [ 11667520  11667016  11670792  11670736  11672400]
 [ 11666904  11672016  11666424  11665560         0]]
size: 20
shape: (4, 5)
dimension: 2


In [ ]:
a=np.random.randint(1,10,5)
a

array([1, 3, 9, 7, 5])

In [ ]:
a=np.linspace(1,10,5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#eye-->

eye=np.eye(3)   #indentity matrix
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# create an array with arange,apply cumsum,cumprod

In [ ]:
a=np.arange(0,9).reshape(3,3)
# b=np.cumsum(a)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
b=np.cumprod(a)
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#1. Create an Array
#Problem: Create a NumPy array from a list of space-separated integers.
#Input format: A list of integers separated by spaces.
#Example: 10 20 30 40 50
# Output format: The NumPy array.
# Example output: [10 20 30 40 50]


a=list(map(int,input("enter:").split()))
arr=np.array(a)
print(arr)

enter:10 20 30 40 50
[10 20 30 40 50]


In [ ]:
# 2. Create an Array of Zeros
# Problem: Create an array of zeros with the specified shape.
# Input format: Two integers representing rows and columns.
# Example: 3 4
# Output format: A 3x4 array of zeros.

a=list(map(int,input("enter:").split()))
b=np.zeros(tuple(a))
b

enter:3 4


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 3. Create an Array of Zeros Like Another
# Problem: Given an array, create a zeros array with the same shape.
# Input format: A list of integers.
# Example: 5 6 7
# Output format: A zeros array with the same shape.
# Example output: [0 0 0]

a=list(map(int,input("enter:").split()))
b=np.zeros_like(a)
b

enter:5 6 7


array([0, 0, 0])

In [ ]:
# 4. Create an Array of Ones
# Problem: Create an array of ones with the specified shape.
# Input format: Two integers representing rows and columns.
# Example: 2 3
# Output format: A 2x3 array of ones.

a=list(map(int,input("enter:").split()))
b=np.ones(tuple(a))
b


enter:2 3


array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 5. Create an Array of Ones Like Another
# Problem: Given an array, create an ones array with the same shape.
# Input format: A list of integers.
# Example: 9 8 7 6
# Output format: An array of ones with the same shape.
# Example output: [1 1 1 1]

a=list(map(int,input("enter:").split()))
b=np.ones_like(a)
b

enter:9 8 7 6


array([1, 1, 1, 1])

In [ ]:
# 6. Create an Uninitialized Array
# Problem: Create an uninitialized array with the given shape.
# Input format: Two integers representing rows and columns.
# Example: 2 2
# Output format: A 2x2 array with arbitrary uninitialized values.

a=list(map(int,input("enter:").split()))
b=np.empty(tuple(a),dtype=int)
b

enter:2 2


array([[9, 8],
       [7, 6]])

In [ ]:
# 7. Create an Array Like Another with Uninitialized Values
# Problem: Given an array, create an uninitialized array with the same shape.
# Input format: A list of integers.
# Example: 1 2 3 4 5
# Output format: An array with uninitialized values.

a=list(map(int,input("enter:").split()))
b=np.empty_like(a)
b


enter:1 2 3 4 5


array([325236114,         0,         0,         0,        48])

In [ ]:
# 8. Create an Array Using arange()
# Problem: Create an array using arange with start, end, and step values.
# Input format: Three integers separated by spaces.
# Example: 5 20 3
# Output format: A NumPy array with values starting from start to before end with step
# size.
# Example output: [5 8 11 14 17]

a=list(map(int,input("enter:").split()))
b=np.arange(a[0],a[1],a[2])
b


enter:5 20 3


array([ 5,  8, 11, 14, 17])

In [ ]:
# 9. Create a Linearly Spaced Array
# Problem: Use linspace to create n equally spaced numbers between start and end.
# Input format: Two floats and an integer: start, end, n.
# Example: 0 1 5
# Output format: An array with n equally spaced values.
# Example output: [0. 0.25 0.5 0.75 1. ]

a=list(map(int,input("enter:").split()))
b=np.linspace(a[0],a[1],a[2])
b


enter:0 1 5


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# 10. Generate Random Numbers (Uniform Distribution)
# Problem: Create an array of random numbers between 0 and 1.
# Input format: Two integers representing rows and columns.
# Example: 3 2
# Output format: A random array with uniform distribution.


a = list(map(int, input("Enter rows and columns: ").split()))
arr = np.random.rand(a[0], a[1])
arr

Enter rows and columns: 3 2


array([[0.63265392, 0.87602067],
       [0.21818724, 0.87887934],
       [0.04160851, 0.53715876]])

In [ ]:
# 11. Generate Normally Distributed Random Numbers
# Problem: Create an array of normally distributed random numbers.
# Input format: Three values: mean, standard deviation, and number of elements.
# Example: 0 1 5
# Output format: A 1D array of n normally distributed values.

