<a href="https://colab.research.google.com/github/Ans365332/6may-file-example/blob/main/Numpy_A_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUMPY---->
#-numpy is basically used for numerical operation on the array
#-Numpy is the library which is used for the numerical computation
#-Numpy,short for Numerical python,is a fundamental library in python for scientific computing.It provide support for large
#,multi-dimensional arrays and matrices, along with collection of high-level mathematical function to operate on these array
#efficiently
#-It work on the homogeneous data

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4])  #It will create an array from numpy package
arr

array([1, 2, 3, 4])

In [ ]:
a=np.arange(1,11)  # it will create an array for particular range
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.ndim     # it will show the dimension

2

In [ ]:
a.shape  # it will  show row and column

(3, 4)

In [ ]:
a.size  # it will show count of element

12

In [ ]:
a.itemsize  #

8

In [ ]:
c=np.array([[1,2],[3,4]],dtype=float)  # by using dtype we can change the data type of array
c

array([[1., 2.],
       [3., 4.]])

In [ ]:
a=np.zeros((3,4))   # it will create the matrix of 0
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a=np.ones((3,4))    #it will create the matrix of 1
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a=np.empty((3,4))    #It will create a matrix with random number in memory
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a=np.linspace(1,10,5)  #it will create an array with particular range with given no. of element
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
a=np.linspace(1,10,5).reshape(5,1,1) #it will create an array with particular range with given no. of element
a

array([[[ 1.  ]],

       [[ 3.25]],

       [[ 5.5 ]],

       [[ 7.75]],

       [[10.  ]]])

In [ ]:
#--Operations between two array-->

In [ ]:
#Q-Generate an array with the range of 1 to 1000,power(2)
#take two array-->addition , multi, substraction

In [ ]:
a=np.arange(1,10)
ar=a**2
ar

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1+a2

array([5, 7, 9])

In [ ]:
a1-a2

array([-3, -3, -3])

In [ ]:
a1*a2

array([ 4, 10, 18])

In [ ]:
ar1=np.array([[1,2],[3,4]])
ar2=np.array([[5,6],[7,8]])    # it will done the matrix multiplication
a=ar1.dot(ar2)
a

array([[19, 22],
       [43, 50]])

In [ ]:
#Random numbers--->

In [ ]:
#random no. generator
a=np.random.default_rng(1)   # it will create the instance for random number
b=a.random((3,4))     #it will generate random number
b

array([[0.51182162, 0.9504637 , 0.14415961, 0.94864945],
       [0.31183145, 0.42332645, 0.82770259, 0.40919914],
       [0.54959369, 0.02755911, 0.75351311, 0.53814331]])

In [ ]:
a=np.array([1,2,3,4])
a.sum()

np.int64(10)

In [ ]:
a.max()

np.int64(4)

In [ ]:
a.min()

np.int64(1)

In [ ]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [ ]:
arr.sum(axis=1)  #sum of row

array([3, 7])

In [ ]:
arr.sum(axis=0)  #sum of column

array([4, 6])

In [ ]:
a=np.array([1,2,3,4])
a.cumsum()  # it is cummulative sum( like fabonacci series)

array([ 1,  3,  6, 10])

In [ ]:
a=np.arange(0,100).reshape(10,1,10)
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74, 75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84, 85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [ ]:
arr=np.ones_like(a) # it will create matrix exactly in dimension like first one but with 1 value
arr

array([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]])

In [ ]:
arr2=np.zeros_like(arr)   # it will create matrix exactly in dimension like first one but with 0 value
arr2

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

In [ ]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr=np.ones_like(a)
print("Array:",arr)
print("size:",arr.size)
print("shape:",arr.shape)
print("dimension:",arr.ndim)

Array: [[1 1 1]
 [1 1 1]
 [1 1 1]]
size: 9
shape: (3, 3)
dimension: 2


In [ ]:
arr2=np.zeros_like(a)
arr2
print("Array:",arr)
print("size:",arr.size)
print("shape:",arr.shape)
print("dimension:",arr.ndim)

9

In [ ]:
a=np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr=np.empty_like(a)
print("Array:",arr)
print("size:",arr.size)
print("shape:",arr.shape)
print("dimension:",arr.ndim)

Array: [[370917920         0  11672240  11667168  11671848]
 [ 11666144  11669184  11668864  11666632  11669664]
 [ 11667520  11667016  11670792  11670736  11672400]
 [ 11666904  11672016  11666424  11665560         0]]
size: 20
shape: (4, 5)
dimension: 2


In [ ]:
a=np.random.randint(1,10,5)
a

array([1, 3, 9, 7, 5])

In [ ]:
a=np.linspace(1,10,5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#eye-->

eye=np.eye(3)   #indentity matrix
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# create an array with arange,apply cumsum,cumprod

In [ ]:
a=np.arange(0,9).reshape(3,3)
# b=np.cumsum(a)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
b=np.cumprod(a)
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#1. Create an Array
#Problem: Create a NumPy array from a list of space-separated integers.
#Input format: A list of integers separated by spaces.
#Example: 10 20 30 40 50
# Output format: The NumPy array.
# Example output: [10 20 30 40 50]


a=list(map(int,input("enter:").split()))
arr=np.array(a)
print(arr)

enter:10 20 30 40 50
[10 20 30 40 50]


In [ ]:
# 2. Create an Array of Zeros
# Problem: Create an array of zeros with the specified shape.
# Input format: Two integers representing rows and columns.
# Example: 3 4
# Output format: A 3x4 array of zeros.

a=list(map(int,input("enter:").split()))
b=np.zeros(tuple(a))
b

enter:3 4


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 3. Create an Array of Zeros Like Another
# Problem: Given an array, create a zeros array with the same shape.
# Input format: A list of integers.
# Example: 5 6 7
# Output format: A zeros array with the same shape.
# Example output: [0 0 0]

a=list(map(int,input("enter:").split()))
b=np.zeros_like(a)
b

enter:5 6 7


array([0, 0, 0])

In [ ]:
# 4. Create an Array of Ones
# Problem: Create an array of ones with the specified shape.
# Input format: Two integers representing rows and columns.
# Example: 2 3
# Output format: A 2x3 array of ones.

a=list(map(int,input("enter:").split()))
b=np.ones(tuple(a))
b


enter:2 3


array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 5. Create an Array of Ones Like Another
# Problem: Given an array, create an ones array with the same shape.
# Input format: A list of integers.
# Example: 9 8 7 6
# Output format: An array of ones with the same shape.
# Example output: [1 1 1 1]

a=list(map(int,input("enter:").split()))
b=np.ones_like(a)
b

enter:9 8 7 6


array([1, 1, 1, 1])

In [ ]:
# 6. Create an Uninitialized Array
# Problem: Create an uninitialized array with the given shape.
# Input format: Two integers representing rows and columns.
# Example: 2 2
# Output format: A 2x2 array with arbitrary uninitialized values.

a=list(map(int,input("enter:").split()))
b=np.empty(tuple(a),dtype=int)
b

enter:2 2


array([[9, 8],
       [7, 6]])

In [ ]:
# 7. Create an Array Like Another with Uninitialized Values
# Problem: Given an array, create an uninitialized array with the same shape.
# Input format: A list of integers.
# Example: 1 2 3 4 5
# Output format: An array with uninitialized values.

a=list(map(int,input("enter:").split()))
b=np.empty_like(a)
b


enter:1 2 3 4 5


array([325236114,         0,         0,         0,        48])

In [ ]:
# 8. Create an Array Using arange()
# Problem: Create an array using arange with start, end, and step values.
# Input format: Three integers separated by spaces.
# Example: 5 20 3
# Output format: A NumPy array with values starting from start to before end with step
# size.
# Example output: [5 8 11 14 17]

a=list(map(int,input("enter:").split()))
b=np.arange(a[0],a[1],a[2])
b


enter:5 20 3


array([ 5,  8, 11, 14, 17])

In [ ]:
# 9. Create a Linearly Spaced Array
# Problem: Use linspace to create n equally spaced numbers between start and end.
# Input format: Two floats and an integer: start, end, n.
# Example: 0 1 5
# Output format: An array with n equally spaced values.
# Example output: [0. 0.25 0.5 0.75 1. ]

a=list(map(int,input("enter:").split()))
b=np.linspace(a[0],a[1],a[2])
b


enter:0 1 5


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# 10. Generate Random Numbers (Uniform Distribution)
# Problem: Create an array of random numbers between 0 and 1.
# Input format: Two integers representing rows and columns.
# Example: 3 2
# Output format: A random array with uniform distribution.


a = list(map(int, input("Enter rows and columns: ").split()))
arr = np.random.rand(a[0], a[1])
arr

Enter rows and columns: 3 2


array([[0.63265392, 0.87602067],
       [0.21818724, 0.87887934],
       [0.04160851, 0.53715876]])

In [ ]:
# 11. Generate Normally Distributed Random Numbers
# Problem: Create an array of normally distributed random numbers.
# Input format: Three values: mean, standard deviation, and number of elements.
# Example: 0 1 5
# Output format: A 1D array of n normally distributed values.



In [ ]:
# Vector Dimensions --> they have value and direction
#Ex--> a=[1,2,3] i+2j+3k

In [ ]:
# Scalar -> no dimension
#1,2,3 only values

In [ ]:
# Tensors-->0dim-->scalar
# Tensor-->1dim-->vector
#Tensor-->2dim-->matrix

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
#print all the rows but print only second and fourth column
#Print the diagonal elements of the matrix (n*n)
#Print the reverse of the last two rows

In [ ]:
#1.
a=np.array([[1,2,3,4],[5,6,7,8]])
a[0:,[1,3]]


array([[2, 4],
       [6, 8]])

In [ ]:
a=np.arange(1,10).reshape(3,3)
b=np.diag(a)
b

array([1, 5, 9])

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a[1:,-1::-1]

array([[ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [ ]:
#Extract first anf fourth row of the given matrix

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a[[0,3],0:]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [ ]:
#Fancy Indexing---->

In [ ]:
#for 1d array--

arr=np.arange(10)
arr[[2,3,6]]
arr1=np.array([5,6,7,8,9,20,30,40,50])
arr1[[1,4,7]]

array([ 6,  9, 40])

In [ ]:
#for 2d--

In [ ]:
a=np.random.rand(3,4)
a

array([[0.02925458, 0.66634865, 0.02997111, 0.61127991],
       [0.29782561, 0.10614265, 0.26467979, 0.40909722],
       [0.96376699, 0.45246089, 0.86162331, 0.64873815]])

In [ ]:
a[[1,2]]

array([[0.29782561, 0.10614265, 0.26467979, 0.40909722],
       [0.96376699, 0.45246089, 0.86162331, 0.64873815]])

In [ ]:
a[[1,2],1:]

array([[0.10614265, 0.26467979, 0.40909722],
       [0.45246089, 0.86162331, 0.64873815]])

In [ ]:
a=np.random.rand(3,3)
a[[0,1,2],[0,1,2]]
a

array([[0.31770023, 0.81460642, 0.20837282],
       [0.26032754, 0.57859429, 0.95105645],
       [0.27545843, 0.33004923, 0.92204836]])

In [ ]:
#Conversion of datatype in array-->
a=np.array([1.0,2.5,3]).astype(int)
a

array([1, 2, 3])

In [ ]:
a=np.array([1,2,3]).astype(float)
a

array([1., 2., 3.])

In [ ]:
# Coversion of element into array-->

In [ ]:
a=[1,2,34]
ar=np.atleast_3d(a)
ar

array([[[ 1],
        [ 2],
        [34]]])

In [ ]:
a=np.random.rand(2,2)
a

array([[0.56905414, 0.07760168],
       [0.00775463, 0.95575215]])

In [ ]:
#Array Manuplation-->

In [ ]:
#split-->
a=np.array_split([1,2,3,4,5,6,],3)
a


[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
import numpy as np

In [ ]:
#Column_stack-->
a=np.array([1,2,3,4])
b=np.array([6,7,8,9])
c=np.row_stack((a,b))
c

/tmp/ipython-input-2078730048.py:4: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  c=np.row_stack((a,b))


array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [ ]:
#Seed()--->
np.random.seed(1) # it will fix the random value
a=np.random.randint(1,10, size=3)
a

array([6, 9, 6])

In [ ]:
#Unique()-->
np.unique(a)

array([6, 9])

In [ ]:
#Ravel()-->it store in flatten array in new array in same size,it can also affect the orignal array
a=np.random.randint(1,20,12).reshape(3,4)
ar=np.ravel(a)
ar

array([11, 15, 19,  5, 10, 18,  1, 14, 10, 10,  8,  2])

In [ ]:
#flatten()---> it will flatten the orignal array without storing in new array,it will not affect the original array
a.flatten()

array([11, 15, 19,  5, 10, 18,  1, 14, 10, 10,  8,  2])