<a href="https://colab.research.google.com/github/Ans365332/6may-file-example/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

--- 1

# Introduction to numpy ----->
-> Numpy is an open source liibrary that is used for handle scientific calculation

# Difference between list and numpy---->
1.List heterogeneous data type and numpy is homogeneous data type

2.List take more memory as compare to numpy

3. List take more execution time as compared to numpy

In [ ]:
#pip install numpy --> for vs code
# !pip install numpy--> for jupyter notebook
# uv and -r requirements.txt --> for uv in vs code

In [1]:
import numpy as np

In [2]:
a=[1,45,78,90]
b=np.array(a)
b

array([ 1, 45, 78, 90])

In [3]:
type(b)

numpy.ndarray

In [ ]:
### User defined array

In [4]:
a=[]
size=int(input("Enter the size of array"))
for i in range(size):
    val=int(input("Enter the value"))
    a.append(val)
b=np.array(a)
b

Enter the size of array4
Enter the value1
Enter the value2
Enter the value3
Enter the value4


array([1, 2, 3, 4])

In [5]:
type(b)

numpy.ndarray

In [6]:
a=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
b=np.array(a)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
b.shape # total rows and column

(3, 4)

In [8]:
b.size # total elements

12

In [ ]:
# how to check dimension of an matrix

In [10]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [11]:
a.ndim

2

--- 2

In [ ]:
#(3).eye-> It will create an array in which diagonal positional element will be 1 and rest all are 0.

In [12]:
a=np.eye(3)  ## row = columns ---> symmetric matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
a=np.eye(3,4) ## row != column --> asymmetric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#(4).diag()--> It will create an array in which we can set our custom value at diagonal position

In [14]:
a=np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [ ]:
#(5)Random Module-->
#(a). Randint()--> It will create an array randomly in the given range

In [15]:
a=np.random.randint(1,10,3)
a

array([6, 9, 8])

In [ ]:
#(b).Rand()--> It will generate random numbers from 0-1

In [16]:
a=np.random.rand(4)
a

array([0.63347104, 0.82833218, 0.83303037, 0.38880864])

In [ ]:
#(C).Seed()--> It will fix or lock our generated data.

In [18]:
np.random.seed(1)
a=np.random.randint(1,10,3)
a

array([6, 9, 6])

In [ ]:
# View vs copy

In [19]:
a=np.array([10,20,30,40,50,60,70,80])
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [20]:
b=a[1:4]
b[:]=0
b

array([0, 0, 0])

In [21]:
a

array([10,  0,  0,  0, 50, 60, 70, 80])

In [ ]:
# copy

In [22]:
a=np.array([10,20,30,40,50,60,70,80])
b=a[1:4].copy()
b[:]=0
b

array([0, 0, 0])

In [23]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
# Reshaping the array
# total rows* columns = total elements

In [24]:
a=np.random.randint(1,50,12)
a

array([16,  1, 17,  2, 13,  8, 46,  7, 26, 21, 38, 19])

In [25]:
a.reshape(2,6)

array([[16,  1, 17,  2, 13,  8],
       [46,  7, 26, 21, 38, 19]])

In [27]:
a.reshape(3,4)

array([[16,  1, 17,  2],
       [13,  8, 46,  7],
       [26, 21, 38, 19]])

In [ ]:
# y=mx+c
# m=matrix -- weights
# x=values --> matrix

# matrix(column) * (row)matrix

In [28]:
a.shape

(12,)

In [30]:
a.reshape(-1,4)  # 12/4

array([[16,  1, 17,  2],
       [13,  8, 46,  7],
       [26, 21, 38, 19]])

In [31]:
a.reshape(2,-1)

array([[16,  1, 17,  2, 13,  8],
       [46,  7, 26, 21, 38, 19]])

In [33]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [34]:
a*2

array([2, 4, 6, 8])

In [35]:
b=np.arange(5,9)
b

array([5, 6, 7, 8])

In [40]:
a=a.reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [41]:
b=b.reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [42]:
a+b

array([[ 6,  8],
       [10, 12]])

In [43]:
a-b

array([[-4, -4],
       [-4, -4]])

In [44]:
a*b

array([[ 5, 12],
       [21, 32]])

In [45]:
a.dot(b) ## this is for matrix multiplication

array([[19, 22],
       [43, 50]])

In [47]:
a=np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [49]:
b=a>10
a[b]

array([11, 12, 13, 14])

In [50]:
a=np.arange(1,4)
a**2

array([1, 4, 9])

In [51]:
a**3

array([ 1,  8, 27])

In [52]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.sum(a)

np.int64(45)

In [54]:
np.sum(a,axis=1) # axis = 1--> row

array([ 6, 15, 24])

In [55]:
np.sum(a,axis=0) # axis = 0--> column

array([12, 15, 18])