<a href="https://colab.research.google.com/github/Ans365332/6may-file-example/blob/main/numpy_A14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [23]:
a=np.array([1,45,78,90])
a

array([ 1, 45, 78, 90])

In [24]:
type(a)

numpy.ndarray

In [25]:
a.ndim

1

In [26]:
b=[1,4,7]
type(b)

list

In [27]:
a+5

array([ 6, 50, 83, 95])

In [28]:
b*2

[1, 4, 7, 1, 4, 7]

In [29]:
p=[[1,2,3,5],[4,5,6,3],[7,8,9,10]]
q=np.array(p)
q

array([[ 1,  2,  3,  5],
       [ 4,  5,  6,  3],
       [ 7,  8,  9, 10]])

In [30]:
type(q)

numpy.ndarray

In [31]:
print("Total dimension = ",q.ndim)
print("Total rows and column =",q.shape)
print("Total elements =",q.size)

Total dimension =  2
Total rows and column = (3, 4)
Total elements = 12


In [ ]:
#Pre-defined functions in numpy--->


In [ ]:
#(1).zeroes()--> It will create an array in which all value will be zero either in one-dimensional or multi-dimensional

In [4]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [ ]:
#it will show value in float

In [5]:
b=np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#(2).ones()---> It will create an array in which all value will be one

In [8]:
a=np.ones(3)
a

array([1., 1., 1.])

In [9]:
b=np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#(3). eye()--> It will create an array in which diagonal positional element will be 1 and rest all are 0

In [10]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#(4). diag---> Using this method,we can set our custom element on diagonal position

In [11]:
a=np.array([1,45,78,90])
a

array([ 1, 45, 78, 90])

In [12]:
b=np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [ ]:
#(5). Random Module
#(a). Randint()---> It will generate random number in a given range

In [15]:
a=np.random.randint(1,10,3)
a

array([5, 1, 3])

In [ ]:
#(b).Rand--> It will generate random number between 0-1

In [17]:
a=np.random.rand(3)
a

array([0.21869075, 0.16514614, 0.13135889])

In [ ]:
# Data--> column add(random numbers)----> model performance 80% --> after refresh---> number update --> model performance 50%

In [ ]:
#(c). seed()--> It will lock or fix your random generated data

In [21]:
np.random.seed(57)
a=np.random.randint(1,10,4)
a

array([7, 6, 7, 9])