<a href="https://colab.research.google.com/github/Ans365332/6may-file-example/blob/main/numpy_A14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np


In [ ]:
a=np.array([1,45,78,90])
a

array([ 1, 45, 78, 90])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

1

In [ ]:
b=[1,4,7]
type(b)

list

In [ ]:
a+5

array([ 6, 50, 83, 95])

In [ ]:
b*2

[1, 4, 7, 1, 4, 7]

In [ ]:
p=[[1,2,3,5],[4,5,6,3],[7,8,9,10]]
q=np.array(p)
q

array([[ 1,  2,  3,  5],
       [ 4,  5,  6,  3],
       [ 7,  8,  9, 10]])

In [ ]:
type(q)

numpy.ndarray

In [ ]:
print("Total dimension = ",q.ndim)
print("Total rows and column =",q.shape)
print("Total elements =",q.size)

Total dimension =  2
Total rows and column = (3, 4)
Total elements = 12


In [ ]:
#Pre-defined functions in numpy--->


In [ ]:
#(1).zeroes()--> It will create an array in which all value will be zero either in one-dimensional or multi-dimensional

In [ ]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [ ]:
#it will show value in float

In [ ]:
b=np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#(2).ones()---> It will create an array in which all value will be one

In [ ]:
a=np.ones(3)
a

array([1., 1., 1.])

In [ ]:
b=np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#(3). eye()--> It will create an array in which diagonal positional element will be 1 and rest all are 0

In [ ]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#(4). diag---> Using this method,we can set our custom element on diagonal position

In [ ]:
a=np.array([1,45,78,90])
a

array([ 1, 45, 78, 90])

In [ ]:
b=np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [ ]:
#(5). Random Module
#(a). Randint()---> It will generate random number in a given range

In [ ]:
a=np.random.randint(1,10,3)
a

array([5, 1, 3])

In [ ]:
#(b).Rand--> It will generate random number between 0-1

In [14]:
a=np.random.rand(3)
a

array([0.93329952, 0.88428175, 0.42433608])

In [ ]:
# Data--> column add(random numbers)----> model performance 80% --> after refresh---> number update --> model performance 50%

In [ ]:
#(c). seed()--> It will lock or fix your random generated data

In [ ]:
np.random.seed(57)
a=np.random.randint(1,10,4)
a

array([7, 6, 7, 9])

In [12]:
import numpy as np

In [ ]:
#view vs copy
#view means modification in original data
#copy means create a duplicate data and when we change into it then it will not reflect the original value

In [15]:
a= np.array([10,20,30,40,50,60,70,80])
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [20]:
b=a[2:5]
b[:]=0

In [21]:
a

array([10, 20,  0,  0,  0, 60, 70, 80])

In [22]:
a= np.array([10,20,30,40,50,60,70,80])
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
b=a[2:5].copy()
b[:]=0

In [23]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
# Reshaping the array

In [24]:
a=np.random.randint(1,50,12)
a

array([11, 14, 29, 25, 44, 18, 31, 41, 38, 15, 36, 32])

In [ ]:
#12 element combination-->
# 1*12 , 12*1
# 2*6 ,6*2
# 3*4 , 4*3

In [25]:
a.reshape(2,6)

array([[11, 14, 29, 25, 44, 18],
       [31, 41, 38, 15, 36, 32]])

In [26]:
a.reshape(3,4)

array([[11, 14, 29, 25],
       [44, 18, 31, 41],
       [38, 15, 36, 32]])

In [27]:
a.reshape(4,3)

array([[11, 14, 29],
       [25, 44, 18],
       [31, 41, 38],
       [15, 36, 32]])

In [28]:
a=np.random.randint(1,100,36)
a

array([16, 93, 18, 74, 62, 82, 93, 23, 84, 98, 58, 50, 53, 21, 39, 15, 75,
       83, 90, 68, 60, 43, 94, 91, 95, 62, 54, 30, 22,  4, 83,  6, 17, 57,
        3, 84])

In [ ]:
# 36 combination element->
# 1*36 , 36*1
# 2*18 , 18*2
#3*12 , 12*3
# 4*9 , 9*4
#6*6

In [29]:
a.reshape(2,18)

array([[16, 93, 18, 74, 62, 82, 93, 23, 84, 98, 58, 50, 53, 21, 39, 15,
        75, 83],
       [90, 68, 60, 43, 94, 91, 95, 62, 54, 30, 22,  4, 83,  6, 17, 57,
         3, 84]])

In [30]:
a.reshape(4,9)

array([[16, 93, 18, 74, 62, 82, 93, 23, 84],
       [98, 58, 50, 53, 21, 39, 15, 75, 83],
       [90, 68, 60, 43, 94, 91, 95, 62, 54],
       [30, 22,  4, 83,  6, 17, 57,  3, 84]])

In [31]:
a.reshape(6,6)

array([[16, 93, 18, 74, 62, 82],
       [93, 23, 84, 98, 58, 50],
       [53, 21, 39, 15, 75, 83],
       [90, 68, 60, 43, 94, 91],
       [95, 62, 54, 30, 22,  4],
       [83,  6, 17, 57,  3, 84]])

In [ ]:
# Operations on Array--->

In [33]:
a=np.arange(1,12,1) # it will work like for loop range for (1,12) with gap of 1
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
a=np.arange(1,20,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [35]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [37]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [38]:
a<5

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False])

In [39]:
b=a<5
a[b]

array([1, 2, 3, 4])

In [40]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [41]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [43]:
a+b  # 1+5 ,2+6 , 3+7 , 4+8

array([[ 6,  8],
       [10, 12]])

In [44]:
a-b

array([[-4, -4],
       [-4, -4]])

In [45]:
a*b  # wrong method

array([[ 5, 12],
       [21, 32]])

In [46]:
a.dot(b)   ### return matrix mutiplication

array([[19, 22],
       [43, 50]])

In [47]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [48]:
a//b

array([[0, 0],
       [0, 0]])

In [49]:
a*2


array([[2, 4],
       [6, 8]])

In [50]:
a**2

array([[ 1,  4],
       [ 9, 16]])

In [51]:
a**3

array([[ 1,  8],
       [27, 64]])

In [52]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.sum(a)

np.int64(45)

In [54]:
## if we want only row wise sum--->

np.sum(a,axis=1)  ## 1+2+3 , 4+5+6 , 7+8+9


array([ 6, 15, 24])

In [55]:
## if we want only column wise sum-->

np.sum(a,axis=0)  # 1+4+7 , 2+5+8 , 3+6+9

array([12, 15, 18])

In [ ]:
#Unique()---> It will remove duplicate element from array and it return 3 array
#arr --> return array of unique value
#return_index=True ---> return array of unique index value.
# return_counts=True ---> return array of each unique value's frequency

In [56]:
arr = np.array([10,20,30,10,20,20,20,20,20,20,20,15])
arr

array([10, 20, 30, 10, 20, 20, 20, 20, 20, 20, 20, 15])

In [58]:
np.unique(arr, return_index=True , return_counts=True)

(array([10, 15, 20, 30]), array([ 0, 11,  1,  2]), array([2, 1, 8, 1]))

In [ ]:
# LinSpace()----> It will return an array in which we will get same gap of values

In [59]:
a=np.linspace(1,2,5)
a       ## in this we have same gap between two value like 1.25-1.=0.25 and 1.5-1.25=0.25

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Hstack() and Vstack()  -----> Hstack() will combine all the arrays in horizontally
# while vstack() will combine all the array in vertically

In [62]:
a=np.arange(1,5)
b=np.arange(5,9)
c=np.arange(9,13)

In [63]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [64]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])